void Sort(int[], int);
void Sort(double[], int);
double GetPower(double, int);
void DemoGetPower(double, int);
void RoundToTens(int&);
void Foo(double);
void FooWithLink(double&);
void FooWithPointer(double*);
void PrintArray(double*, int);
void PrintArray(int*, int);
void PrintArray(char*, int);
void PrintArray(bool*, int);
int ValueIndexInArray(int*, int, int);
void PrintOnlyLetters(char*, int);
int* MakeRandomArray(int);
int* ReadArray(int);
int CountPositiveValues(int*, int);
void Breakpoints();
void Breakpoints2();
